name: Publish to Sonatype Central

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Publish to Sonatype Central
        env:
          MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.PGP_SECRET_BASE64 }}
          MILL_PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        run: ./mill mill-docker.publishSonatypeCentral